
#допоміжні величини анімації
FPS = 60

#величини екрану
MAIN_WINDOW_COLOR = '#D9D9D9'
WINDOW_HEIGHT, WINDOW_WIDTH = 1400, 800 

#величини кнопки
BUTTON_MENU_WIDTH = 600
BUTTON_MENU_HEIGHT = 120
BUTTON_COLOR = '#8A0000'
BUTTON_PLACEMENT_HEIGHT= 120
BUTTON_PLACEMENT_WIDTH = 400

#ACTIVE_SCREEN = "menu"



#Величини полів для битв
PLACE_LENGTH = 600